config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "flats#index"
  get "/flats/:id", to: "flats#show", as: :flat
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
    def index
        url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
        @flats = JSON.parse(URI.open(url).read)
    end

    def show 
        url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
        @flats = JSON.parse(URI.open(url).read)
        @id = params[:id].to_i
        @flat = @flats.select { |flat| flat['id'] == @id }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>


<% @flats.each do |flat|%>
    <div><%= flat["name"] %></div>
    <img src=<%= flat["imageUrl"] %> alt="" style="width: 300px;">
    <div><%= flat['price'] %></div>
    <%= link_to "show", flat_path(flat["id"]) %>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat[0]['name'] %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>